# Overview
 This project is a VM Designed to be an all in one internet radio streaming solution based on linux. The idea is that This will be eventually exapanded to connect to a second server that hold all music files and work through gathering all the metadata and analyzing the files to make it easier to mix from. The eventual solution is that not only will this be enough to analyze all files but would also act as a means to plug and play with a timecode turntable setup connected to a thin client and stream from the same VM.
# Tools
 For this project I'm going to need a few tools here in order for this to work. The list is as follows:
   - Azuracast (https://www.azuracast.com/about/#what-is-azuracast): This is an all-in-one solution to make your own web radio content. It comes with a full interface as well that can be used to monitor the stream and set up a webclient public page for patrons. 
   - Mixxx (https://www.mixxx.org/): As the idea is for me to basically stick with linux this narrows my options on DJ software. Mixxx is actually a free DJ software but is constantly improving and very full featured. If I were to get any new hardware and had the time I could even make a custom setup to handle the hardware. Other reason we're using this is that it comes with support for icecast ( and by extension azuracast) so I can  just hot key over and stream my performances. Another bonus to this is that you can mass scan your music library to get the Beats per Minute (BPM) and Key of each track as well and save it to the file. 
   - MusicBrainz Picard (https://picard.musicbrainz.org/): This program is designed to scan the music files to identify tracks and wha CD they're from as well as update the tags for them. This would be something to run in the background if I had a large set of music that I didn't have information for. 
   - Audacity (https://www.audacityteam.org/): Multifeatured program that allows to splice tracks if need be along with live recording 
   - A Digital Ocean account (https://www.digitalocean.com/): This will be needed to handle the broadcast and bandwith
   - A Virtual Machine: Pretty obvious as this is running within a Proxmox VM at present. Will be using Debain as the oS since every program can be installed with it and despite the slow updates it stays stable longer before any breaking changes are made. Linux Mint (LMDE version) would be a second choice. 
   - Wyse Terminal: As the eventual expansion would call for this to be an all in one solution. I will attempt to make the VM available to use as a thin client to access everything and input the hardware ( Turntables, keyboard, mouse, ect) instead of a full on machine. Also the hope is that the lag will be minimal since the connections within the home are all local hardwired networks. The idea is that all the work would be done on the VM along with the processing and the input would work just fine as long as not too much is running in the background. When not actively recording the VM can be set to scan the library and update the listings and easily be monitored. 

# Setup
